### ISSUE TITLE
Map the joypad buttons to rpc commands

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/walking-controllers#22]
To simplify the setup of the demo we should map the joypad buttons to the rpc port (e.g. press A to prepare the robot, press B to start walking ...)

**Comment by DanielePucci** [comment]
This is really useful. Probably @kouroshD can take upon this?

**Comment by kouroshD** [comment]
@DanielePucci  Yes, it is a good idea. when I get acquainted with the software, we can surely do it.
@GiulioRomualdi  Just the matter of curiosity, what are the functionalities of joypad buttons now?

**Comment by kouroshD** [comment]
@DanielePucci yes, it is a good idea, when I start implementing, I will do this as well.

**Comment by GiulioRomualdi** [comment]
@kuroshD, right now the buttons have no functionality. The main utility of the joypad is sending the desired walking orientation and speed by means of the left joipad axis. 

To understand if one of the button is pressed you may use [’getButton’](http://www.yarp.it/classyarp_1_1dev_1_1IJoypadController.html#a71875d6605e7deb30003587f898b8321) method.

**Comment by GiulioRomualdi** [comment]
Done in https://github.com/robotology/walking-controllers/commit/df831d855e834b67309547a87bb368285287b2d9
