### ISSUE TITLE
Unused attributes in the code

### ISSUE THREAD

**Issue by traversaro** [robotology/walking-controllers#29]
## `WalkingModule::m_firstStep`
The [`WalkingModule::m_firstStep`](https://github.com/robotology/walking-controllers/blob/6c406b2179b5289c52e76e5c4814d80d292024ba/modules/Walking_module/include/WalkingModule.hpp#L59) attribute is updated once, but it is never used by the program. Instead the `WalkingFK::m_firstStep` is actually used. 

Perhaps it could make sense to remove `WalkingModule::m_firstStep`?

## `WalkingFSM::Stance`

The `Stance` state of the FSM is never used. Perhaps it could make sense to remove it?

**Comment by GiulioRomualdi** [comment]
This will be fixed by #33

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/walking-controllers/pull/33 .
