### ISSUE TITLE
Check why when not receiving end effector pose from walking-teleoperation IK from walking-controller is going to 0 values

### ISSUE THREAD

**Issue by fjandrad** [robotology/walking-controllers#38]
In theory, when no pose is received it should use the previous value. So in the initial configuration it should not move, but we see the arms going towards the body.
We should understand why and correct it.
cc @GiulioRomualdi

**Comment by fjandrad** [comment]
It was mentioned in this [PR](https://github.com/robotology/walking-teleoperation/pull/23)

**Comment by GiulioRomualdi** [comment]
There is a bug in the `walking-controllers`. And the bug is related to the resetting of the `m_retargetingClient` object. 

I fixed the bug and I opened a PR: https://github.com/robotology/walking-controllers/pull/40

**Comment by GiulioRomualdi** [comment]
The PR #40 was merged. We can close the issue
