### ISSUE TITLE
Release v0.3.3

### ISSUE THREAD

**Issue by traversaro** [robotology/walking-controllers#70]
For the release v2020.11 of the robotology-superbuild, it would be convenient to do a release v0.3.3 to include the fix in https://github.com/robotology/walking-controllers/pull/62 that ensures that walking-controllers compiles fine with iDynTree 2.0.0 . 
See https://github.com/robotology/robotology-superbuild/pull/530 .

**Comment by traversaro** [comment]
@S-Dafarra @GiulioRomualdi

**Comment by GiulioRomualdi** [comment]
yes, I'm fine I think we can release master

**Comment by GiulioRomualdi** [comment]
Done in https://github.com/robotology/walking-controllers/releases/tag/v0.3.3
