### ISSUE TITLE
While using the retargeting walking, the hands seems to raise if the robot walks for a "long" distance

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/walking-controllers#85]
We observed this recently. It seems that the arms keep going up while walking, eventually leading to the zombie walking that makes the robot to fall. We need to investigate what could be the cause of this issue.

**Comment by GiulioRomualdi** [comment]
The issue was related to the CoM gain in the IK. Indeed the gain on the CoM height was set to zero
