### ISSUE TITLE
Error on exporting env var with "-"

### ISSUE THREAD

**Issue by hu-yue** [robotology/walking-controllers#9]
@GiulioRomualdi it seems that "-" is not accepted as part of an environmental variable name, as I got the error:
```
bash: export: `walking-controllers_DIR=/home/yuehu/Software/iCub_SW/walking-controllers/install': not a valid identifier
```
The error disappeard by changing "-" with "_".

**Comment by traversaro** [comment]
I never realized that, but this is a big drawback of having CMake package names with a `-` in their name.

**Comment by GiulioRomualdi** [comment]
Fixed in `devel` branch.
